apiVersion: v1
kind: ServiceAccount
metadata:
  name: mapek-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mapek-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mapek-role-binding
subjects:
- kind: ServiceAccount
  name: mapek-sa
  namespace: default
roleRef:
  kind: Role
  name: mapek-role
  apiGroup: rbac.authorization.k8s.io
