apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mapek-edit-role-binding
subjects:
- kind: ServiceAccount
  name: mapek-sa
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io