apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mapek-role-binding
subjects:
- kind: ServiceAccount
  name: mapek-sa
roleRef:
  kind: Role
  name: mapek-role
  apiGroup: rbac.authorization.k8s.io