apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapek-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapek
  template:
    metadata:
      labels:
        app: mapek
    spec:
      containers:
        - name: mapek-container
          image: quay.io/jcepedav/payment-mapek:latest
          envFrom:
            - configMapRef:
                name: mapek-payment-config
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
      serviceAccountName: mapek-sa
